services:
  - type: web
    name: face-attendance
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13